{
 "title": "JVM metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kubernetes_namespace)"
   },
   { "name": "app", "label": "app", "query": "label_values(app)" }
  ]
 },
 "panels": [
  { "title": "Thread State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "jvm_threads_state",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "jvm_threads_state{app=\"$app\",kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "jvm_threads_used",
   "type": "graph",
   "description": "Sum of JVM threads currently running across pods",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_current{app=\"$app\",kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "jvm_threads_started",
   "type": "graph",
   "description": "Rate of JVM threads started across pods",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_threads_started_total{app=\"$app\",kubernetes_namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Value"
    }
   ]
  },
  { "title": "Memory and Classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "jvm_memory_bytes_heap",
   "type": "graph",
   "description": "Sum of JVM Heap memory across pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{app=\"$app\",kubernetes_namespace=\"$namespace\",area=\"heap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{app=\"$app\",kubernetes_namespace=\"$namespace\",area=\"heap\"})",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "jvm_memory_bytes_non_heap",
   "type": "graph",
   "description": "Sum of JVM Non Heap memory across pods",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{app=\"$app\",kubernetes_namespace=\"$namespace\",area=\"nonheap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{app=\"$app\",kubernetes_namespace=\"$namespace\",area=\"nonheap\"})",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "jvm_classes_loaded",
   "type": "graph",
   "description": "Rate of Java Classes loaded across pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_classes_loaded_total{app=\"$app\",kubernetes_namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "jvm_classes_unloaded",
   "type": "graph",
   "description": "Rate of Java Classes unloaded across pods",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_classes_unloaded_total{app=\"$app\",kubernetes_namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "gc_events_count",
   "type": "graph",
   "description": "Rate of Garbage collection events across pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_count{app=\"$app\",kubernetes_namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "gc_events_duration",
   "type": "graph",
   "description": "Garbage collection event duration across pods",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{app=\"$app\",kubernetes_namespace=\"$namespace\"}[5m]))/sum(increase(jvm_gc_collection_seconds_count{app=\"$app\",kubernetes_namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Value"
    }
   ]
  }
 ]
}