{
 "title": "JVM metrics",
 "description": "Dashboard to monitor Java Virtual machine metrics collected through JMX exporter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kubernetes_namespace)"
   },
   { "name": "app", "label": "app", "query": "label_values(app)" }
  ]
 },
 "panels": [
  { "title": "System and Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "process_cpu_load",
   "type": "graph",
   "description": "Process CPU consumption across pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(increase(java_lang_OperatingSystem_ProcessCpuLoad{app=\"$app\",kubernetes_namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "system_cpu_load",
   "type": "graph",
   "description": "System CPU consumption rate across pods",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(increase(java_lang_OperatingSystem_SystemCpuLoad{app=\"$app\",kubernetes_namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "compilation_time",
   "type": "graph",
   "description": "Average Compilation times across pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(increase(java_lang_Compilation_TotalCompilationTime{app=\"$app\",kubernetes_namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "total_memory_bytes_free",
   "type": "graph",
   "description": "Free physical memory size across pods",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(java_lang_OperatingSystem_FreePhysicalMemorySize{app=\"$app\",kubernetes_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Threads and Classes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "jvm_threads_state",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "jvm_threads_state{app=\"$app\",kubernetes_namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "jvm_threads_used",
     "type": "graph",
     "description": "Sum of JVM threads currently running across pods",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_threads_current{app=\"$app\",kubernetes_namespace=\"$namespace\"})",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "jvm_threads_started",
     "type": "graph",
     "description": "Rate of JVM threads started across pods",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jvm_threads_started_total{app=\"$app\",kubernetes_namespace=\"$namespace\"}[5m]))",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "jvm_classes_loaded",
     "type": "graph",
     "description": "Rate of Java Classes loaded across pods",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jvm_classes_loaded_total{app=\"$app\",kubernetes_namespace=\"$namespace\"}[5m]))",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "jvm_classes_unloaded",
     "type": "graph",
     "description": "Rate of Java Classes unloaded across pods",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jvm_classes_unloaded_total{app=\"$app\",kubernetes_namespace=\"$namespace\"}[5m]))",
       "legendFormat": "Value"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "jvm_memory_bytes_heap",
     "type": "graph",
     "description": "Sum of JVM Heap memory across pods",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_memory_bytes_used{app=\"$app\",kubernetes_namespace=\"$namespace\",area=\"heap\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{app=\"$app\",kubernetes_namespace=\"$namespace\",area=\"heap\"})",
       "legendFormat": "Committed"
      }
     ]
    },
    {
     "title": "jvm_memory_bytes_non_heap",
     "type": "graph",
     "description": "Sum of JVM Non Heap memory across pods",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_memory_bytes_used{app=\"$app\",kubernetes_namespace=\"$namespace\",area=\"nonheap\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{app=\"$app\",kubernetes_namespace=\"$namespace\",area=\"nonheap\"})",
       "legendFormat": "Committed"
      }
     ]
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "gc_events_count",
   "type": "graph",
   "description": "Rate of Garbage collection events across pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(jvm_gc_collection_seconds_count{app=\"$app\",kubernetes_namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "gc_events_duration",
   "type": "graph",
   "description": "Garbage collection event duration across pods",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{app=\"$app\",kubernetes_namespace=\"$namespace\"}[5m]))/sum(increase(jvm_gc_collection_seconds_count{app=\"$app\",kubernetes_namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Value"
    }
   ]
  }
 ]
}