{
 "title": "Server metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kubernetes_namespace)"
   },
   { "name": "app", "query": "label_values(app)" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Server Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(server_request_count{app=\"$app\",kubernetes_namespace=\"$namespace\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(server_response_duration_seconds_sum{app=\"$app\",kubernetes_namespace=\"$namespace\"}[$interval]))/sum(increase(server_response_duration_seconds_count{app=\"$app\",kubernetes_namespace=\"$namespace\"}[$interval]))"
    }
   ]
  },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "server_requests",
   "type": "graph",
   "description": "Number of requests received by the Application ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(server_request_count{app=\"$app\",kubernetes_namespace=\"$namespace\"}[$interval]))"
    }
   ]
  },
  {
   "title": "server_response_time",
   "type": "graph",
   "description": "Response time in Seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(server_response_duration_seconds_sum{app=\"$app\",kubernetes_namespace=\"$namespace\"}[$interval]))/sum(increase(server_response_duration_seconds_count{app=\"$app\",kubernetes_namespace=\"$namespace\"}[$interval]))"
    }
   ]
  },
  {
   "title": "server_response_buckets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(server_response_duration_seconds_bucket{app=\"$app\",kubernetes_namespace=\"$namespace\"}[$interval])) by (le))"
    }
   ]
  },
  {
   "title": "process_cpu_seconds",
   "type": "graph",
   "description": "Total CPU time utilized in Seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(process_cpu_seconds_total{app=\"$app\",kubernetes_namespace=\"$namespace\"}[$interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "process_resident_memory",
   "type": "graph",
   "description": "Total Memory allocated to process",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(process_resident_memory_bytes{app=\"$app\",kubernetes_namespace=\"$namespace\"}[$interval]))"
    }
   ]
  },
  { "title": "Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "server_requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(server_request_count{app=\"$app\",kubernetes_namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "server_response_duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(server_response_duration_seconds_sum{app=\"$app\",kubernetes_namespace=\"$namespace\"}[$interval])/increase(server_response_duration_seconds_count{app=\"$app\",kubernetes_namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "process_cpu_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{app=\"$app\",kubernetes_namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "process_resident_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(process_resident_memory_bytes{app=\"$app\",kubernetes_namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}